version: "2.1"
orbs:
  cypress: cypress-io/cypress@3
  jq: circleci/jq@3.0.1
jobs:
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
            - .cache/Cypress
            - project
          root: ~/

  run-tests-in-parallel:
    executor: cypress/default
    parallelism: 8
    steps:
      - attach_workspace:
          at: ~/
      - jq/install
      - run:
          name: Parse CYPRESS_FILES_LIST environment variable
          command: |
            CYPRESS_FILES_LIST=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r .files)
            echo "export CYPRESS_FILES_LIST=$CYPRESS_FILES_LIST" >> $BASH_ENV
      - run:
          name: Print CYPRESS_FILES_LIST
          command: |
            echo "CYPRESS_FILES_LIST=$CYPRESS_FILES_LIST"
            printenv CYPRESS_FILES_LIST
      - run:
          name: Parse CYPRESS_CLIENT_NAME environment variable
          command: |
            CYPRESS_CLIENT_NAME="$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r .client)"
            echo "export CYPRESS_CLIENT_NAME=$CYPRESS_CLIENT_NAME" >> $BASH_ENV
      - run:
          name: Print CYPRESS_CLIENT_NAME
          command: |
            echo "CYPRESS_CLIENT_NAME=$CYPRESS_CLIENT_NAME"
            printenv CYPRESS_CLIENT_NAME
      - run:
          name: Parse CYPRESS_PET_NAME environment variable
          command: |
            CYPRESS_PET_NAME=$(echo '<< pipeline.trigger_parameters.webhook.body >>' | jq -r .pet)
            echo "export CYPRESS_PET_NAME=$CYPRESS_PET_NAME" >> $BASH_ENV
      - run:
          name: Print CYPRESS_PET_NAME
          command: |
            echo "CYPRESS_PET_NAME=$CYPRESS_PET_NAME"
            printenv CYPRESS_PET_NAME
      - cypress/run-tests:
          cypress-command: npx cypress run

workflows:
  use-my-orb:
    jobs:
      - install-and-persist:
          name: Install & Persist To Workspace
      - run-tests-in-parallel:
          name: Run Tests in Parallel
          requires:
            - Install & Persist To Workspace
