version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
        post-checkout:
          - run:
            name: Set up environment variables
            steps:
              - jq/install
              - run:
                name: Extract bucket variable
                environment:
                  WEBHOOK_BUCKET: << pipeline.trigger_parameters.webhook.body | jq -r '.bucket' >>
                command: echo "CYPRESS_BUCKET=$WEBHOOK_BUCKET" >> $BASH_ENV
